# Copyright 2023 vbn
# https://github.com/vbn/miryoku_zmk

name: 'vbn-swweeep-build'
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["vbn_swweeep_left nice_view_adapter nice_view","vbn_swweeep_right nice_view_adapter nice_view"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_PM_SOFT_OFF=y"]'
      branches: '["zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll"]'
